# events {
#     worker_connections 1024;
# }

# http {

#     upstream back {
#         server back:8002;
#     }

#     upstream frontend {
#         server frontend:80;
#     }

#     server {
#         listen 8080;

#         # Frontend
#         location / {
#             proxy_pass http://frontend;
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#         }

#         location /api/back/ {
#             proxy_pass http://api/back/;
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#         }
#     }
# }